### ISSUE TITLE
Nord UART... and model of exercise bike

### ISSUE THREAD

**Issue by m8e** [codaris/UnderDeskBike#2]
"This is a personal project designed for this exact model of exercise bike. It might work for other exercise bikes but probably not without some modification"

Question 1:  what is the brand and model of the exercise bike?

Question 2:  the exercise bike uses Nord UART

How was this determined?  

This looks like the UART software interface here

https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/include/bluetooth/services/nus.html

Interesting project, thanks for activating my neural network 😉

**Comment by codaris** [comment]
[This is a link](https://www.costco.ca/exerpeutic-under-desk-bike.product.100528330.html) to the exercise bike.  You might find it available in other countries under different model names.  I actually haven't been able to find a good source for it.

Every Bluetooth GATT profile has a GUID associated with it.  The Connect nRF Android app that I used to scan for Bluetooth devices has a database of all the common profiles and tells you exactly what kind of device it is.
