### ISSUE TITLE
Which bike?

### ISSUE THREAD

**Issue by AndreasOM** [codaris/UnderDeskBike#3]
In your README you mention "designed for this exact model of exercise bike".
You might want to add info which bike that is,
to make it easier for others to reuse your project, and learn from it.

**Comment by nchowning** [comment]
Came here to say this. I'd love to play around with it but I don't know what bike this is for.

**Comment by nixxou** [comment]
Same here, i would love to know the exact model of the bike (or at least the name of the android app, so i can find compatible bikes)

**Comment by codaris** [comment]
@nixxou it is an Exerpeutic 7149.  It would probably work with any model of bike that uses the same underlying technology.  It seems pretty hacked together so I imagine many bikes use the same system.
